version: "3.7"
services:
  postgres:
    image: postgres:13.3
    env_file:
      - ./apivirtualmachines/.env
    ports: 
      - '5432:5432'
    volumes:
      - apivirtualmachines-db:/var/lib/postgresql/data

  apivirtualmachines:
    build:
      context: .
    environment:
      DB_HOST: postgres
    env_file:
      - ./apivirtualmachines/.env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  apivirtualmachines-db: